version: "3.7"

services:
  # Application
  app:
    build:
      context: ./app/
    ports:
      - 8080:8080
    restart: always

  # Reverse proxy
  apache:
    build:
      context: ./apache/
    ports:
      - 8000:80
    restart: always
