version: "3.7"

services:
  # Application
  app:
    build:
      context: ./app/
    ports:
      - 8080:8080

  # Reverse proxy
  apache:
    build:
      context: ./apache/
    ports:
      - 8000:80

  # Load testing
  loadtesting:
    depends_on:
      - apache
      - app
    build:
      context: ./loadtesting/
